### PR TITLE
Revamped

### PR DESCRIPTION
**Pull request by tomquirk**
@theocodes, I noticed you recently took over the repo; congrats! To get the ball rolling, I've "revamped" the project to follow the latest Brunch plugin writing guides. This includes:

- minor file restructuring (bringing everything to root dir)
- using the official Brunch eslint config
- new test suite using mocha

Also included:
- dependency version bumps

The original code has barely changed. If you think any revisions are needed, let me know; I'm keen to contribute to the project in the future 😃

### CODE REVIEW

**Comment by nblackburn** [comment]
**minor file restructuring (bringing everything to root dir)**

The reason the code was kept out of root is to separate it from the masses of configuration files developers have grown accustom to. This allows for a recognizable place for them to find the code rather than being mangled with everything else.

**new test suite using mocha**

I am not sure there is much of a reason behind this other than preference as Brunch uses Ava (_which is objectively better_).

**other points**

There was no need to remove editorconfig, it's a universal standard that most text editors use to create the same development environment regardless of editor.

It's down to @theocodes in regards to what happens but i am still keeping an eye on things and may chime in from time to time.

**Comment by tomquirk** [comment]
All fair points. I'm just going off other popular Brunch plugins ([here](https://github.com/babel/babel-brunch) and [here](https://github.com/brunch/coffee-script-brunch)) as well as the [official boilerplate](https://github.com/brunch/brunch-boilerplate-plugin).

File structure isn't the biggest deal, but it's better if we stick to the norm.

I agree, Ava is cool - I suppose it's up to @theocodes, but most all the Brunch plugins I've seen use Mocha - guess its not that big of a deal either, I'll at least add tests to the Ava suite.

Didn't mean to remove editor config - I'll put that back in 😄

**Comment by tomquirk** [comment]
@theocodes if you're happy to merge it, would be great if you could wait until the 1st of October - I want that [Hacktoberfest](https://hacktoberfest.digitalocean.com/) tshirt 😂 (don't judge)

**Comment by tomquirk** [comment]
@theocodes see what you think

**Pull request merged**
